import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Merriweather,
  Outfit,
  Poppins,
} from "next/font/google";
import "./globals.css";
import LenisSetup from "~/_components/LenisSetup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriWeather = Merriweather({
  variable: "--font-mw",
});

const outfit = Outfit({
  variable: "--font-outfit",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${merriWeather.variable}
          ${outfit.variable}
          ${poppins.variable}
          antialiased`}
      >
        <LenisSetup>{children}</LenisSetup>
      </body>
    </html>
  );
}
